---
apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: n8n
spec:
  selector:
    app: n8n
  type: LoadBalancer
  loadBalancerIP: 192.168.178.225
  ports:
    - port: 5678
      targetPort: 5678
      name: http
      protocol: TCP
