---
apiVersion: v1
kind: Service
metadata:
  name: tailscale-service
  namespace: tailscale
  annotations:
    metallb.universe.tf/allow-shared-ip: tailscale-svc
spec:
  loadBalancerIP: 192.168.178.222
  selector:
    app: tailscale
  type: LoadBalancer
  ports:
    - name: web
      port: 5252
      protocol: TCP
      targetPort: 8080
