---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager
  namespace: nginx-proxy-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy-manager
  template:
    metadata:
      labels:
        app: nginx-proxy-manager
    spec:
      containers:
        - name: nginx-proxy-manager
          image: jc21/nginx-proxy-manager:2.13.5@sha256:cd9eba29ca132cb006729f2cb2660126453f84818c2f7d75963ad7b61ef696bd
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 81
              name: admin
          env:
            - name: DISABLE_IPV6
              value: "true"
          volumeMounts:
            - name: npm-pvc
              mountPath: /data
            - name: npm-pvc
              mountPath: /etc/letsencrypt
      volumes:
        - name: npm-pvc
          persistentVolumeClaim:
            claimName: npm-pvc
