apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: immich
  annotations:
    metallb.universe.tf/allow-shared-ip: immich-svc
spec:
  loadBalancerIP: 192.168.178.225
  selector:
    app: immich
  ports:
    - protocol: TCP
      port: 2283
      targetPort: 2283
  type: LoadBalancer
