---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pgadmin/pv.yaml
  - pgadmin/pvc.yaml
  - pgadmin/secret.yaml
  - pgadmin/deployment.yaml
  - pgadmin/service.yaml
  - postgres/pv.yaml
  - postgres/pvc.yaml
  - postgres/secret.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
