---
vps:
  hosts:
    vps1:
      ansible_host: "{{ lookup('env', 'VPS_HOST') }}"
      ansible_user: "{{ lookup('env', ''VPS_USER') }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'VPS_SSH_KEY_PATH') }}"
