---
apiVersion: v1
kind: Service
metadata:
  name: actualbudget-service
  namespace: actualbudget
spec:
  selector:
    app: actualbudget
  type: LoadBalancer
  loadBalancerIP: 192.168.178.223
  ports:
    - port: 5006
      targetPort: 5006
      name: http
      protocol: TCP
