---
name: CI - Validate Cluster
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
    paths:
      - ansible/**
      - apps/**
      - clusters/**
      - talos/**
      - utils/**
jobs:
  trivy:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Trivy config scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config,secret"
          severity: "HIGH,CRITICAL"
          scan-ref: "."
          exit-code: '1'
  yamllint:
    name: YAML Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: 3.x
      - name: Install yamllint
        run: |
          pip install yamllint
      - name: Run yamllint
        run: |
          yamllint -c .yamllint apps/ clusters/ utils/ ansible/ talos/
  kubeconform:
    name: K8s Schema Validation
    runs-on: ubuntu-latest
    needs: yamllint
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Run Kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest@sha256:85dbef6b4b312b99133decc9c6fc9495e9fc5f92293d4ff3b7e1b30f5611823c
        with:
          entrypoint: /kubeconform
          args: -summary -output json -ignore-missing-schemas -schema-location default -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json -verbose apps/ clusters/ utils/
